/*
###############################################################
#  Generated by:      Cadence Innovus 20.11-s130_1
#  OS:                Linux x86_64(Host ID fatima.novalocal)
#  Generated on:      Mon Jan  6 22:38:48 2025
#  Design:            BATCHARGERctr
#  Command:           saveNetlist BATCHARGERctr_pr.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.14-s108_1
// Generated on: Jan  6 2025 15:48:16 WET (Jan  6 2025 15:48:16 UTC)
// Verification Directory fv/BATCHARGERctr 
module BATCHARGERctr (
	cc, 
	tc, 
	cv, 
	imonen, 
	vmonen, 
	tmonen, 
	so, 
	vbat, 
	ibat, 
	tbat, 
	vcutoff, 
	vpreset, 
	tempmin, 
	tempmax, 
	tmax, 
	iend, 
	clk, 
	en, 
	rstz, 
	vtok, 
	dvdd, 
	dgnd);
   output cc;
   output tc;
   output cv;
   output imonen;
   output vmonen;
   output tmonen;
   output so;
   input [7:0] vbat;
   input [7:0] ibat;
   input [7:0] tbat;
   input [7:0] vcutoff;
   input [7:0] vpreset;
   input [7:0] tempmin;
   input [7:0] tempmax;
   input [7:0] tmax;
   input [7:0] iend;
   input clk;
   input en;
   input rstz;
   input vtok;
   input dvdd;
   input dgnd;

   // Internal wires
   wire [2:0] state;
   wire [15:0] charge_timer;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED10;
   wire UNCONNECTED11;
   wire UNCONNECTED12;
   wire UNCONNECTED13;
   wire UNCONNECTED14;
   wire UNCONNECTED15;
   wire UNCONNECTED16;
   wire UNCONNECTED17;
   wire UNCONNECTED18;
   wire UNCONNECTED19;
   wire UNCONNECTED20;
   wire UNCONNECTED21;
   wire logic_1_1_net;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_109;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_132;
   wire n_133;
   wire n_134;
   wire n_135;
   wire n_136;
   wire n_137;
   wire n_138;
   wire n_139;
   wire n_140;
   wire n_141;
   wire n_142;
   wire n_143;
   wire n_144;
   wire n_145;
   wire n_146;
   wire n_147;
   wire n_148;
   wire n_149;
   wire n_150;
   wire n_151;
   wire n_152;
   wire n_153;
   wire n_154;
   wire n_155;
   wire n_156;
   wire n_157;
   wire n_158;
   wire n_159;
   wire n_160;
   wire n_161;
   wire n_162;
   wire n_163;
   wire n_164;
   wire n_165;
   wire n_166;
   wire n_167;
   wire n_168;
   wire n_169;
   wire n_170;
   wire n_171;
   wire n_172;
   wire n_173;
   wire n_174;
   wire n_175;
   wire n_176;
   wire n_177;
   wire n_178;
   wire n_179;
   wire n_180;
   wire n_181;
   wire n_182;
   wire n_183;
   wire n_184;
   wire n_185;
   wire n_186;
   wire n_187;
   wire n_188;
   wire n_189;
   wire n_190;
   wire n_191;
   wire n_192;
   wire n_193;
   wire n_194;
   wire n_195;
   wire n_196;
   wire n_197;
   wire n_198;
   wire n_199;
   wire n_200;
   wire n_201;
   wire n_202;
   wire n_203;
   wire n_204;
   wire n_205;
   wire n_206;
   wire n_207;
   wire n_208;
   wire n_209;
   wire n_210;
   wire n_211;
   wire n_212;
   wire n_213;
   wire n_214;
   wire n_215;
   wire n_216;
   wire n_217;
   wire n_218;
   wire n_219;
   wire n_220;
   wire n_221;
   wire n_222;
   wire n_223;
   wire n_224;
   wire n_225;
   wire n_226;
   wire n_227;
   wire n_228;
   wire n_229;
   wire n_230;
   wire n_231;
   wire n_232;
   wire n_233;
   wire n_234;
   wire n_235;
   wire n_236;
   wire n_237;
   wire n_238;
   wire n_239;
   wire n_240;
   wire n_241;
   wire n_242;
   wire n_243;
   wire n_244;
   wire n_245;
   wire n_246;
   wire n_247;
   wire n_248;
   wire n_249;
   wire n_250;
   wire n_251;
   wire n_252;
   wire n_253;
   wire n_254;
   wire n_255;
   wire n_256;
   wire n_257;
   wire n_258;
   wire n_259;
   wire n_260;
   wire n_261;
   wire n_262;
   wire n_263;
   wire n_264;
   wire n_265;

   assign imonen = cv ;

   AN2EHD FE_RC_0_0 (.O(n_257),
	.I1(en),
	.I2(vtok));
   DBFRSBEHD tmonen_reg_reg (.Q(tmonen),
	.QB(UNCONNECTED),
	.D(n_265),
	.CKB(clk),
	.RB(logic_1_1_net),
	.SB(rstz));
   DBFRBEHD cc_reg_reg (.Q(cc),
	.QB(UNCONNECTED0),
	.D(n_264),
	.CKB(clk),
	.RB(rstz));
   DBFRBEHD cv_reg_reg (.Q(cv),
	.QB(UNCONNECTED1),
	.D(n_263),
	.CKB(clk),
	.RB(rstz));
   DBFRBEHD tc_reg_reg (.Q(tc),
	.QB(UNCONNECTED2),
	.D(n_260),
	.CKB(clk),
	.RB(rstz));
   MUX2CHD g9160__2398 (.O(n_265),
	.S(n_257),
	.A(tmonen),
	.B(n_254));
   DBFRBEHD \state_reg[0]  (.Q(state[0]),
	.QB(UNCONNECTED3),
	.D(n_258),
	.CKB(clk),
	.RB(rstz));
   OAI13BHD g9163__5107 (.O(n_264),
	.A1(n_73),
	.B1(n_255),
	.B2(n_262),
	.B3(n_261));
   OAI13BHD g9165__6260 (.O(n_263),
	.A1(n_80),
	.B1(n_259),
	.B2(n_262),
	.B3(n_261));
   DBFRBEHD \state_reg[1]  (.Q(state[1]),
	.QB(UNCONNECTED4),
	.D(n_256),
	.CKB(clk),
	.RB(rstz));
   OAI13BHD g9164__4319 (.O(n_260),
	.A1(n_77),
	.B1(n_259),
	.B2(n_253),
	.B3(n_261));
   OAI22CHD g9168__8428 (.O(n_258),
	.A1(n_261),
	.A2(n_262),
	.B1(n_243),
	.B2(n_257));
   OAI22CHD g9167__5526 (.O(n_256),
	.A1(n_261),
	.A2(n_255),
	.B1(n_240),
	.B2(n_257));
   OR2B1CHD g9169__6783 (.O(n_254),
	.I1(n_255),
	.B1(n_262));
   DBFRBEHD \state_reg[2]  (.Q(state[2]),
	.QB(UNCONNECTED5),
	.D(n_251),
	.CKB(clk),
	.RB(rstz));
   INVCKDHD g9172 (.O(n_262),
	.I(n_253));
   ND3CHD g9171__3680 (.O(n_255),
	.I1(n_249),
	.I2(n_247),
	.I3(n_252));
   OAI12CHD g9173__1617 (.O(n_253),
	.A1(n_250),
	.B1(state[2]),
	.B2(n_252));
   OAI22CHD g9170__2802 (.O(n_251),
	.A1(n_261),
	.A2(n_259),
	.B1(n_244),
	.B2(n_257));
   AOI22BHD g9175__1705 (.O(n_250),
	.A1(n_246),
	.A2(n_234),
	.B1(n_45),
	.B2(n_239));
   AOI13BHD g9176__5122 (.O(n_249),
	.A1(n_248),
	.B1(state[2]),
	.B2(state[0]),
	.B3(n_242));
   NR2CHD g9177__8246 (.O(n_248),
	.I1(n_241),
	.I2(n_181));
   OR3B2CHD g9174__7098 (.O(n_259),
	.I1(n_245),
	.B1(n_247),
	.B2(n_252));
   OAI22CHD g9179__6131 (.O(n_246),
	.A1(n_216),
	.A2(n_235),
	.B1(state[2]),
	.B2(n_247));
   OAI13BHD g9178__1881 (.O(n_245),
	.A1(n_238),
	.B1(n_244),
	.B2(n_243),
	.B3(n_242));
   OA13EHD g9181__5115 (.O(n_241),
	.A1(n_237),
	.B1(n_243),
	.B2(n_240),
	.B3(n_231));
   OAI112BHD g9180__7482 (.O(n_239),
	.A1(n_247),
	.B1(n_252),
	.C1(n_243),
	.C2(n_233));
   AOI22BHD g9182__4733 (.O(n_238),
	.A1(n_221),
	.A2(n_227),
	.B1(n_243),
	.B2(n_236));
   OR2B1CHD g9183__6161 (.O(n_237),
	.I1(n_236),
	.B1(n_229));
   AOI13BHD g9184__9315 (.O(n_235),
	.A1(n_232),
	.B1(n_244),
	.B2(n_228),
	.B3(n_230));
   ND2DHD g9185__9945 (.O(n_234),
	.I1(state[0]),
	.I2(n_233));
   OA112EHD g9186__2883 (.O(n_232),
	.A1(n_240),
	.B1(n_231),
	.C1(state[2]),
	.C2(n_230));
   OAI112BHD g9188__2346 (.O(n_229),
	.A1(n_231),
	.B1(n_226),
	.C1(state[0]),
	.C2(n_228));
   NR2CHD g9189__1666 (.O(n_233),
	.I1(n_242),
	.I2(n_244));
   OR2EHD g9190__7410 (.O(n_227),
	.I1(n_226),
	.I2(n_231));
   OAI22CHD g9192__6417 (.O(n_226),
	.A1(n_225),
	.A2(state[1]),
	.B1(n_240),
	.B2(n_228));
   AOI112BHD g9193__5477 (.O(n_242),
	.A1(n_223),
	.B1(n_166),
	.C1(n_43),
	.C2(iend[7]));
   AOI22BHD g9195__2398 (.O(n_231),
	.A1(n_244),
	.A2(n_228),
	.B1(state[2]),
	.B2(n_225));
   DBFRBEHD \charge_timer_reg[15]  (.Q(charge_timer[15]),
	.QB(UNCONNECTED6),
	.D(n_224),
	.CKB(clk),
	.RB(rstz));
   AO22CHD g9202__5107 (.O(n_224),
	.A1(charge_timer[15]),
	.A2(n_219),
	.B1(charge_timer[13]),
	.B2(n_200));
   INVCKDHD g9201 (.O(n_228),
	.I(n_225));
   OAI112BHD g9198__6260 (.O(n_223),
	.A1(n_220),
	.B1(n_82),
	.C1(n_105),
	.C2(n_165));
   DBFRBEHD \charge_timer_reg[14]  (.Q(charge_timer[14]),
	.QB(UNCONNECTED7),
	.D(n_222),
	.CKB(clk),
	.RB(rstz));
   MAO222EHD g9203__4319 (.O(n_225),
	.A1(n_217),
	.B1(n_72),
	.C1(n_97));
   OAI13BHD g9206__8428 (.O(n_222),
	.A1(n_218),
	.B1(n_214),
	.B2(charge_timer[14]),
	.B3(n_213));
   AO12EHD g9187__5526 (.O(n_221),
	.A1(n_236),
	.B1(n_96),
	.B2(n_64));
   NR2BHD g9204__6783 (.O(n_220),
	.I1(n_190),
	.I2(n_212));
   OAI12CHD g9210__3680 (.O(n_219),
	.A1(n_211),
	.B1(n_207),
	.B2(charge_timer[14]));
   DBFRBEHD \charge_timer_reg[13]  (.Q(charge_timer[13]),
	.QB(UNCONNECTED8),
	.D(n_215),
	.CKB(clk),
	.RB(rstz));
   ND2DHD g9209__1617 (.O(n_218),
	.I1(charge_timer[14]),
	.I2(n_210));
   OAI22CHD g9212__2802 (.O(n_217),
	.A1(n_133),
	.A2(n_206),
	.B1(n_130),
	.B2(n_129));
   AOI12CHD g9191__1705 (.O(n_236),
	.A1(state[2]),
	.B1(n_216),
	.B2(n_230));
   DBFRBEHD \charge_timer_reg[12]  (.Q(charge_timer[12]),
	.QB(UNCONNECTED9),
	.D(n_209),
	.CKB(clk),
	.RB(rstz));
   OAI22CHD g9213__5122 (.O(n_215),
	.A1(n_208),
	.A2(n_214),
	.B1(charge_timer[13]),
	.B2(n_213));
   OAI112BHD g9214__8246 (.O(n_212),
	.A1(n_204),
	.B1(n_169),
	.C1(n_142),
	.C2(n_151));
   INVCKDHD g9216 (.O(n_211),
	.I(n_210));
   OAI13BHD g9220__7098 (.O(n_209),
	.A1(n_205),
	.B1(n_197),
	.B2(charge_timer[12]),
	.B3(n_198));
   OAI12CHD g9217__6131 (.O(n_210),
	.A1(n_208),
	.B1(n_207),
	.B2(charge_timer[13]));
   MAO222CHD g9194__1881 (.O(n_252),
	.A1(n_202),
	.B1(n_12),
	.C1(tbat[7]));
   MAO222CHD g9196__5115 (.O(n_247),
	.A1(n_201),
	.B1(n_16),
	.C1(tempmax[7]));
   DBFRBEHD \charge_timer_reg[10]  (.Q(charge_timer[10]),
	.QB(UNCONNECTED10),
	.D(n_196),
	.CKB(clk),
	.RB(rstz));
   DBFRBEHD \charge_timer_reg[11]  (.Q(charge_timer[11]),
	.QB(UNCONNECTED11),
	.D(n_199),
	.CKB(clk),
	.RB(rstz));
   AOI222BHD g9226__7482 (.O(n_206),
	.A1(n_132),
	.A2(n_131),
	.B1(n_194),
	.B2(n_128),
	.C1(n_126),
	.C2(n_127));
   MAO222CHD g9199__4733 (.O(n_216),
	.A1(n_195),
	.B1(n_18),
	.C1(vcutoff[7]));
   ND2DHD g9222__6161 (.O(n_205),
	.I1(charge_timer[12]),
	.I2(n_203));
   DBFRBEHD \charge_timer_reg[9]  (.Q(charge_timer[9]),
	.QB(UNCONNECTED12),
	.D(n_193),
	.CKB(clk),
	.RB(rstz));
   MAOI1CHD g9225__9315 (.O(n_204),
	.A1(n_56),
	.A2(n_57),
	.B1(n_189),
	.B2(n_187));
   NR2CHD g9223__9945 (.O(n_208),
	.I1(n_203),
	.I2(n_106));
   MAO222CHD g9207__2883 (.O(n_202),
	.A1(n_184),
	.B1(n_21),
	.C1(tbat[6]));
   MAO222CHD g9208__2346 (.O(n_201),
	.A1(n_185),
	.B1(n_9),
	.C1(tempmax[6]));
   NR3BHD g9219__1666 (.O(n_200),
	.I1(n_213),
	.I2(charge_timer[15]),
	.I3(n_39));
   OAI22CHD g9227__7410 (.O(n_199),
	.A1(n_198),
	.A2(charge_timer[11]),
	.B1(n_197),
	.B2(n_191));
   OAI13BHD g9231__6417 (.O(n_196),
	.A1(n_188),
	.B1(n_167),
	.B2(n_40),
	.B3(n_192));
   MAO222CHD g9215__5477 (.O(n_195),
	.A1(n_177),
	.B1(n_79),
	.C1(vcutoff[6]));
   DBFRBEHD \charge_timer_reg[8]  (.Q(charge_timer[8]),
	.QB(UNCONNECTED13),
	.D(n_186),
	.CKB(clk),
	.RB(rstz));
   AO222EHD g9238__2398 (.O(n_194),
	.A1(n_125),
	.A2(n_124),
	.B1(n_179),
	.B2(n_74),
	.C1(n_172),
	.C2(n_178));
   OAI13BHD g9239__5107 (.O(n_193),
	.A1(n_183),
	.B1(n_173),
	.B2(charge_timer[9]),
	.B3(n_192));
   OAI12CHD g9229__6260 (.O(n_203),
	.A1(n_191),
	.B1(n_207),
	.B2(charge_timer[11]));
   OAI22CHD g9245__4319 (.O(n_190),
	.A1(n_76),
	.A2(n_189),
	.B1(n_38),
	.B2(tmax[7]));
   OR3B2CHD g9233__8428 (.O(n_213),
	.I1(n_198),
	.B1(charge_timer[12]),
	.B2(charge_timer[11]));
   OAI12CHD g9235__5526 (.O(n_188),
	.A1(charge_timer[10]),
	.B1(n_107),
	.B2(n_182));
   OAI112BHD g9236__6783 (.O(n_187),
	.A1(n_176),
	.B1(n_75),
	.C1(charge_timer[7]),
	.C2(tmax[7]));
   OAI13BHD g9246__3680 (.O(n_186),
	.A1(n_175),
	.B1(n_155),
	.B2(charge_timer[8]),
	.B3(n_192));
   MAO222CHD g9221__1617 (.O(n_185),
	.A1(n_164),
	.B1(n_1),
	.C1(tempmax[5]));
   DBFRBEHD \charge_timer_reg[7]  (.Q(charge_timer[7]),
	.QB(UNCONNECTED14),
	.D(n_174),
	.CKB(clk),
	.RB(rstz));
   MAO222CHD g9228__2802 (.O(n_184),
	.A1(n_168),
	.B1(n_11),
	.C1(tbat[5]));
   ND2DHD g9242__1705 (.O(n_183),
	.I1(charge_timer[9]),
	.I2(n_182));
   AOI12CHD g9241__5122 (.O(n_191),
	.A1(n_261),
	.B1(n_180),
	.B2(n_181));
   OR2EHD g9243__8246 (.O(n_198),
	.I1(n_192),
	.I2(n_180));
   OR3B2CHD g9258__7098 (.O(n_179),
	.I1(n_178),
	.B1(n_171),
	.B2(n_170));
   MAO222CHD g9232__6131 (.O(n_177),
	.A1(n_161),
	.B1(n_14),
	.C1(vcutoff[5]));
   AO13EHD g9249__1881 (.O(n_176),
	.A1(n_160),
	.B1(charge_timer[3]),
	.B2(n_83),
	.B3(tmax[3]));
   OAI12CHD g9248__5115 (.O(n_175),
	.A1(charge_timer[8]),
	.B1(n_156),
	.B2(n_261));
   OAI13BHD g9253__7482 (.O(n_174),
	.A1(n_162),
	.B1(n_135),
	.B2(charge_timer[7]),
	.B3(n_192));
   AO12CHD g9250__4733 (.O(n_182),
	.A1(n_261),
	.B1(n_173),
	.B2(n_181));
   DBFRBEHD \charge_timer_reg[5]  (.Q(charge_timer[5]),
	.QB(UNCONNECTED15),
	.D(n_157),
	.CKB(clk),
	.RB(rstz));
   ND2CHD g9259__6161 (.O(n_172),
	.I1(n_171),
	.I2(n_170));
   AOI22BHD g9264__9315 (.O(n_169),
	.A1(n_153),
	.A2(n_139),
	.B1(n_138),
	.B2(n_86));
   OAI112BHD g9265__9945 (.O(n_189),
	.A1(n_152),
	.B1(n_102),
	.C1(charge_timer[8]),
	.C2(n_101));
   DBFRBEHD \charge_timer_reg[1]  (.Q(charge_timer[1]),
	.QB(UNCONNECTED16),
	.D(n_158),
	.CKB(clk),
	.RB(rstz));
   DBFRBEHD \charge_timer_reg[6]  (.Q(charge_timer[6]),
	.QB(UNCONNECTED17),
	.D(n_163),
	.CKB(clk),
	.RB(rstz));
   DBFRBEHD \charge_timer_reg[3]  (.Q(charge_timer[3]),
	.QB(UNCONNECTED18),
	.D(n_159),
	.CKB(clk),
	.RB(rstz));
   MAO222CHD g9247__2883 (.O(n_168),
	.A1(n_146),
	.B1(n_25),
	.C1(tbat[4]));
   OR2EHD g9256__2346 (.O(n_167),
	.I1(charge_timer[10]),
	.I2(n_173));
   OR3B2CHD g9255__1666 (.O(n_180),
	.I1(n_173),
	.B1(charge_timer[9]),
	.B2(charge_timer[10]));
   AN4B1BHD g9234__7410 (.O(n_166),
	.I1(n_148),
	.I2(n_67),
	.I3(n_33),
	.B1(n_165));
   MAO222CHD g9240__6417 (.O(n_164),
	.A1(n_147),
	.B1(n_8),
	.C1(tempmax[4]));
   DBFRBEHD \charge_timer_reg[2]  (.Q(charge_timer[2]),
	.QB(UNCONNECTED19),
	.D(n_150),
	.CKB(clk),
	.RB(rstz));
   DBFRBEHD \charge_timer_reg[4]  (.Q(charge_timer[4]),
	.QB(UNCONNECTED20),
	.D(n_154),
	.CKB(clk),
	.RB(rstz));
   OAI13BHD g9261__5477 (.O(n_163),
	.A1(n_149),
	.B1(n_112),
	.B2(charge_timer[6]),
	.B3(n_192));
   OAI12CHD g9257__2398 (.O(n_162),
	.A1(charge_timer[7]),
	.B1(n_136),
	.B2(n_261));
   MAO222CHD g9254__5107 (.O(n_161),
	.A1(n_137),
	.B1(n_62),
	.C1(vcutoff[4]));
   OAI22CHD g9262__6260 (.O(n_160),
	.A1(n_84),
	.A2(n_134),
	.B1(n_89),
	.B2(n_66));
   OAI13BHD g9277__4319 (.O(n_159),
	.A1(n_144),
	.B1(n_51),
	.B2(n_22),
	.B3(n_192));
   OAI13BHD g9300__8428 (.O(n_158),
	.A1(n_143),
	.B1(n_118),
	.B2(charge_timer[1]),
	.B3(n_192));
   OAI13BHD g9270__5526 (.O(n_157),
	.A1(n_145),
	.B1(n_78),
	.B2(n_7),
	.B3(n_192));
   OAI222BHD g9273__6783 (.O(n_171),
	.A1(n_140),
	.A2(n_141),
	.B1(n_243),
	.B2(vpreset[1]),
	.C1(n_48),
	.C2(state[0]));
   AN2EHD g9266__3680 (.O(n_156),
	.I1(n_155),
	.I2(n_181));
   DBFRBEHD \charge_timer_reg[0]  (.Q(charge_timer[0]),
	.QB(UNCONNECTED21),
	.D(n_119),
	.CKB(clk),
	.RB(rstz));
   OR2B1CHD g9267__1617 (.O(n_173),
	.I1(n_155),
	.B1(charge_timer[8]));
   OAI13BHD g9285__2802 (.O(n_154),
	.A1(n_123),
	.B1(n_98),
	.B2(charge_timer[4]),
	.B3(n_192));
   OAI22CHD g9283__1705 (.O(n_153),
	.A1(n_49),
	.A2(n_117),
	.B1(n_88),
	.B2(n_87));
   INVCKDHD g9281 (.O(n_152),
	.I(n_151));
   OAI13BHD g9298__5122 (.O(n_150),
	.A1(n_121),
	.B1(n_99),
	.B2(charge_timer[2]),
	.B3(n_192));
   OAI12CHD g9271__8246 (.O(n_149),
	.A1(charge_timer[6]),
	.B1(n_113),
	.B2(n_261));
   MAO222CHD g9263__7098 (.O(n_148),
	.A1(n_109),
	.B1(n_3),
	.C1(iend[3]));
   MAO222CHD g9252__6131 (.O(n_147),
	.A1(n_114),
	.B1(n_6),
	.C1(tempmax[3]));
   MAO222CHD g9274__1881 (.O(n_146),
	.A1(n_110),
	.B1(n_26),
	.C1(tbat[3]));
   OAI12CHD g9275__5115 (.O(n_145),
	.A1(charge_timer[5]),
	.B1(n_100),
	.B2(n_122));
   OAI12CHD g9291__7482 (.O(n_144),
	.A1(charge_timer[3]),
	.B1(n_104),
	.B2(n_120));
   OAI12CHD g9305__4733 (.O(n_143),
	.A1(charge_timer[1]),
	.B1(n_111),
	.B2(n_261));
   AOI22BHD g9284__6161 (.O(n_142),
	.A1(charge_timer[8]),
	.A2(n_103),
	.B1(n_70),
	.B2(n_71));
   ND2DHD g9292__9315 (.O(n_170),
	.I1(n_141),
	.I2(n_140));
   OAI112BHD g9288__9945 (.O(n_151),
	.A1(n_139),
	.B1(n_116),
	.C1(n_115),
	.C2(n_41));
   OAI22CHD g9282__2883 (.O(n_138),
	.A1(n_108),
	.A2(n_92),
	.B1(n_55),
	.B2(n_54));
   MAO222CHD g9272__2346 (.O(n_137),
	.A1(n_94),
	.B1(n_61),
	.C1(vcutoff[3]));
   AN2EHD g9276__1666 (.O(n_136),
	.I1(n_135),
	.I2(n_181));
   OAI112BHD g9286__7410 (.O(n_134),
	.A1(n_93),
	.B1(n_27),
	.C1(charge_timer[2]),
	.C2(tmax[2]));
   OR2B1CHD g9278__6417 (.O(n_155),
	.I1(n_135),
	.B1(charge_timer[7]));
   MOAI1CHD g9297__5477 (.O(n_133),
	.A1(n_132),
	.A2(n_131),
	.B1(n_130),
	.B2(n_129));
   OA22EHD g9296__2398 (.O(n_128),
	.A1(n_127),
	.A2(n_126),
	.B1(n_125),
	.B2(n_124));
   ND2CHD g9289__5107 (.O(n_123),
	.I1(charge_timer[4]),
	.I2(n_122));
   ND2CHD g9304__6260 (.O(n_121),
	.I1(charge_timer[2]),
	.I2(n_120));
   OAI22CHD g9308__4319 (.O(n_119),
	.A1(n_192),
	.A2(charge_timer[0]),
	.B1(n_118),
	.B2(n_257));
   ND2DHD g9307__8428 (.O(n_117),
	.I1(n_116),
	.I2(n_115));
   OAI112BHD g9310__5526 (.O(n_141),
	.A1(n_81),
	.B1(n_35),
	.C1(n_69),
	.C2(vbat[0]));
   MAO222CHD g9287__6783 (.O(n_114),
	.A1(n_60),
	.B1(n_4),
	.C1(tempmax[2]));
   AN2EHD g9290__3680 (.O(n_113),
	.I1(n_112),
	.I2(n_181));
   NR2BHD g9341__1617 (.O(n_111),
	.I1(charge_timer[0]),
	.I2(n_207));
   MAO222CHD g9299__2802 (.O(n_110),
	.A1(n_59),
	.B1(n_20),
	.C1(tbat[2]));
   MAO222CHD g9302__1705 (.O(n_109),
	.A1(n_58),
	.B1(n_13),
	.C1(iend[2]));
   AOI112BHD g9301__5122 (.O(n_139),
	.A1(n_90),
	.B1(n_85),
	.C1(n_91),
	.C2(n_108));
   OR2B1CHD g9294__8246 (.O(n_135),
	.I1(n_112),
	.B1(charge_timer[6]));
   OAI112BHD g9293__7098 (.O(n_230),
	.A1(vbat[6]),
	.B1(vbat[7]),
	.C1(n_63),
	.C2(vbat[5]));
   NR2BHD g9333__6131 (.O(n_107),
	.I1(charge_timer[9]),
	.I2(n_207));
   NR2BHD g9339__1881 (.O(n_106),
	.I1(charge_timer[12]),
	.I2(n_207));
   AOI22BHD g9317__5115 (.O(n_105),
	.A1(n_68),
	.A2(iend[4]),
	.B1(n_42),
	.B2(iend[5]));
   NR2BHD g9337__7482 (.O(n_104),
	.I1(charge_timer[2]),
	.I2(n_207));
   AN2EHD g9303__4733 (.O(n_103),
	.I1(n_102),
	.I2(n_101));
   NR2BHD g9336__6161 (.O(n_100),
	.I1(charge_timer[4]),
	.I2(n_207));
   AO12EHD g9322__9315 (.O(n_120),
	.A1(n_261),
	.B1(n_181),
	.B2(n_99));
   AO12EHD g9312__9945 (.O(n_122),
	.A1(n_261),
	.B1(n_181),
	.B2(n_98));
   AOI22BHD g9350__2883 (.O(n_97),
	.A1(n_95),
	.A2(vpreset[7]),
	.B1(n_96),
	.B2(vbat[7]));
   OAI22CHD g9352__2346 (.O(n_131),
	.A1(vpreset[5]),
	.A2(n_96),
	.B1(n_95),
	.B2(vbat[5]));
   OAI22CHD g9347__1666 (.O(n_140),
	.A1(vpreset[1]),
	.A2(n_96),
	.B1(n_95),
	.B2(vbat[1]));
   AOI22BHD g9353__7410 (.O(n_127),
	.A1(n_95),
	.A2(vpreset[4]),
	.B1(n_96),
	.B2(vbat[4]));
   AOI22BHD g9354__6417 (.O(n_124),
	.A1(n_95),
	.A2(vpreset[3]),
	.B1(n_96),
	.B2(vbat[3]));
   ND2DHD g9343__5477 (.O(n_192),
	.I1(n_181),
	.I2(n_257));
   AOI22BHD g9311__2398 (.O(n_94),
	.A1(n_50),
	.A2(n_46),
	.B1(n_15),
	.B2(vbat[2]));
   AO222EHD g9309__5107 (.O(n_93),
	.A1(charge_timer[2]),
	.A2(tmax[2]),
	.B1(n_44),
	.B2(tmax[0]),
	.C1(charge_timer[1]),
	.C2(tmax[1]));
   OR2EHD g9306__6260 (.O(n_92),
	.I1(n_91),
	.I2(n_90));
   AOI222BHD g9316__4319 (.O(n_89),
	.A1(charge_timer[5]),
	.A2(tmax[5]),
	.B1(charge_timer[4]),
	.B2(n_53),
	.C1(charge_timer[6]),
	.C2(tmax[6]));
   AOI22BHD g9355__8428 (.O(n_178),
	.A1(n_95),
	.A2(vpreset[2]),
	.B1(n_96),
	.B2(vbat[2]));
   ND2CHD g9321__5526 (.O(n_116),
	.I1(n_88),
	.I2(n_87));
   INVDHD g9314 (.O(n_86),
	.I(n_85));
   INVDHD g9344 (.O(n_84),
	.I(n_83));
   OR3B2CHD g9342__6783 (.O(n_82),
	.I1(ibat[6]),
	.B1(n_65),
	.B2(iend[6]));
   AOI22BHD g9345__3680 (.O(n_81),
	.A1(n_95),
	.A2(vbat[0]),
	.B1(state[0]),
	.B2(vpreset[0]));
   ND2DHD g9338__1617 (.O(n_80),
	.I1(cv),
	.I2(n_261));
   MOAI1CHD g9349__2802 (.O(n_129),
	.A1(n_95),
	.A2(n_79),
	.B1(n_95),
	.B2(vpreset[6]));
   AO222EHD g9348__1705 (.O(n_125),
	.A1(state[0]),
	.A2(vpreset[3]),
	.B1(n_95),
	.B2(vbat[3]),
	.C1(state[2]),
	.C2(vcutoff[3]));
   OR3B2CHD g9313__5122 (.O(n_112),
	.I1(n_98),
	.B1(charge_timer[5]),
	.B2(charge_timer[4]));
   INVDHD g9357 (.O(n_207),
	.I(n_181));
   OR2EHD g9315__8246 (.O(n_78),
	.I1(charge_timer[5]),
	.I2(n_98));
   ND2DHD g9335__7098 (.O(n_77),
	.I1(tc),
	.I2(n_261));
   AOI13BHD g9324__6131 (.O(n_76),
	.A1(n_34),
	.B1(charge_timer[7]),
	.B2(n_75),
	.B3(tmax[7]));
   AO222EHD g9326__1881 (.O(n_74),
	.A1(state[0]),
	.A2(vpreset[2]),
	.B1(n_95),
	.B2(vbat[2]),
	.C1(state[2]),
	.C2(vcutoff[2]));
   ND2DHD g9334__5115 (.O(n_73),
	.I1(cc),
	.I2(n_261));
   AO222EHD g9331__7482 (.O(n_72),
	.A1(state[2]),
	.A2(vcutoff[7]),
	.B1(n_95),
	.B2(vbat[7]),
	.C1(state[0]),
	.C2(vpreset[7]));
   AO222EHD g9328__4733 (.O(n_132),
	.A1(state[2]),
	.A2(vcutoff[5]),
	.B1(n_95),
	.B2(vbat[5]),
	.C1(state[0]),
	.C2(vpreset[5]));
   AO222EHD g9329__6161 (.O(n_126),
	.A1(state[2]),
	.A2(vcutoff[4]),
	.B1(n_95),
	.B2(vbat[4]),
	.C1(state[0]),
	.C2(vpreset[4]));
   AOI222BHD g9330__9315 (.O(n_130),
	.A1(state[2]),
	.A2(vcutoff[6]),
	.B1(n_95),
	.B2(vbat[6]),
	.C1(state[0]),
	.C2(vpreset[6]));
   OR2EHD g9318__9945 (.O(n_102),
	.I1(n_71),
	.I2(n_70));
   AN2EHD g9358__2883 (.O(n_69),
	.I1(n_95),
	.I2(vpreset[0]));
   AN2B1CHD g9360__2346 (.O(n_68),
	.I1(n_67),
	.B1(ibat[4]));
   NR3BHD g9351__1666 (.O(n_83),
	.I1(n_28),
	.I2(n_52),
	.I3(n_66));
   OAI12CHD g9362__7410 (.O(n_88),
	.A1(n_108),
	.B1(charge_timer[12]),
	.B2(n_37));
   OAI12CHD g9364__6417 (.O(n_165),
	.A1(n_65),
	.B1(n_10),
	.B2(iend[6]));
   AN2B1CHD g9365__5477 (.O(n_181),
	.I1(state[2]),
	.B1(n_64));
   AOI12CHD g9340__2398 (.O(n_63),
	.A1(n_62),
	.B1(n_29),
	.B2(n_61));
   MAO222CHD g9327__5107 (.O(n_60),
	.A1(n_36),
	.B1(n_17),
	.C1(tempmax[1]));
   MAO222CHD g9325__6260 (.O(n_59),
	.A1(n_31),
	.B1(n_5),
	.C1(tbat[1]));
   MAO222CHD g9323__4319 (.O(n_58),
	.A1(n_32),
	.B1(n_19),
	.C1(iend[1]));
   NR2CHD g9320__8428 (.O(n_85),
	.I1(n_57),
	.I2(n_56));
   AN2EHD g9319__5526 (.O(n_90),
	.I1(n_55),
	.I2(n_54));
   AN2B1CHD g9359__6783 (.O(n_53),
	.I1(tmax[4]),
	.B1(n_52));
   OR2EHD g9361__3680 (.O(n_51),
	.I1(charge_timer[3]),
	.I2(n_99));
   OAI112BHD g9346__1617 (.O(n_50),
	.A1(n_0),
	.B1(vcutoff[0]),
	.C1(n_47),
	.C2(vcutoff[1]));
   AN2EHD g9363__2802 (.O(n_70),
	.I1(n_49),
	.I2(n_30));
   OR3B2CHD g9356__1705 (.O(n_98),
	.I1(n_99),
	.B1(charge_timer[3]),
	.B2(charge_timer[2]));
   MAOI1CHD g9370__5122 (.O(n_48),
	.A1(n_244),
	.A2(n_47),
	.B1(vcutoff[1]),
	.B2(n_244));
   AOI22BHD g9369__8246 (.O(n_46),
	.A1(n_47),
	.A2(vcutoff[1]),
	.B1(n_2),
	.B2(vcutoff[2]));
   OAI22CHD g9367__7098 (.O(n_45),
	.A1(n_240),
	.A2(state[2]),
	.B1(n_244),
	.B2(state[1]));
   OAI12CHD g9368__6131 (.O(n_44),
	.A1(n_99),
	.B1(n_118),
	.B2(n_23));
   INVDHD g9388 (.O(n_96),
	.I(n_95));
   INVDHD g9366 (.O(n_261),
	.I(n_257));
   OR2CHD g9380__1881 (.O(n_65),
	.I1(iend[7]),
	.I2(n_43));
   MOAI1CHD g9372__5115 (.O(n_115),
	.A1(charge_timer[11]),
	.A2(tmax[3]),
	.B1(charge_timer[11]),
	.B2(tmax[3]));
   MOAI1CHD g9373__7482 (.O(n_101),
	.A1(charge_timer[9]),
	.A2(tmax[1]),
	.B1(charge_timer[9]),
	.B2(tmax[1]));
   MAOI1CHD g9374__4733 (.O(n_55),
	.A1(charge_timer[14]),
	.A2(tmax[6]),
	.B1(tmax[6]),
	.B2(charge_timer[14]));
   MAOI1CHD g9371__6161 (.O(n_91),
	.A1(charge_timer[13]),
	.A2(tmax[5]),
	.B1(tmax[5]),
	.B2(charge_timer[13]));
   OR2CHD g9379__9315 (.O(n_67),
	.I1(iend[5]),
	.I2(n_42));
   INVDHD g9332 (.O(n_41),
	.I(n_49));
   NR2CHD g9394__2883 (.O(n_71),
	.I1(tmax[1]),
	.I2(n_40));
   ND2CHD g9399__2346 (.O(n_64),
	.I1(state[0]),
	.I2(n_240));
   NR2CHD g9385__1666 (.O(n_56),
	.I1(tmax[6]),
	.I2(n_39));
   ND2DHD g9382__7410 (.O(n_57),
	.I1(n_38),
	.I2(tmax[7]));
   ND2CHD g9386__6417 (.O(n_108),
	.I1(charge_timer[12]),
	.I2(n_37));
   AN2EHD g9401__5477 (.O(n_95),
	.I1(n_244),
	.I2(n_243));
   OR2B1CHD g9378__2398 (.O(n_36),
	.I1(tempmax[0]),
	.B1(tbat[0]));
   ND2CHD g9391__5107 (.O(n_35),
	.I1(state[2]),
	.I2(vcutoff[0]));
   NR2CHD g9389__6260 (.O(n_34),
	.I1(tmax[0]),
	.I2(charge_timer[8]));
   OR2B1CHD g9376__4319 (.O(n_33),
	.I1(iend[4]),
	.B1(ibat[4]));
   OR2B1CHD g9383__8428 (.O(n_32),
	.I1(iend[0]),
	.B1(ibat[0]));
   OR2B1CHD g9381__5526 (.O(n_31),
	.I1(tbat[0]),
	.B1(tempmin[0]));
   OR2B1CHD g9384__6783 (.O(n_87),
	.I1(tmax[3]),
	.B1(charge_timer[11]));
   OR2B1CHD g9387__3680 (.O(n_49),
	.I1(tmax[2]),
	.B1(charge_timer[10]));
   OR2B1CHD g9377__1617 (.O(n_30),
	.I1(charge_timer[10]),
	.B1(tmax[2]));
   ND2CHD g9392__2802 (.O(n_29),
	.I1(vbat[2]),
	.I2(vbat[1]));
   NR2CHD g9393__1705 (.O(n_28),
	.I1(tmax[4]),
	.I2(charge_timer[4]));
   OR2EHD g9390__5122 (.O(n_27),
	.I1(tmax[3]),
	.I2(charge_timer[3]));
   ND2CHD g9397__8246 (.O(n_75),
	.I1(charge_timer[8]),
	.I2(tmax[0]));
   NR2CHD g9396__7098 (.O(n_66),
	.I1(tmax[6]),
	.I2(charge_timer[6]));
   OR2B1CHD g9395__6131 (.O(n_54),
	.I1(tmax[5]),
	.B1(charge_timer[13]));
   NR2CHD g9398__1881 (.O(n_52),
	.I1(tmax[5]),
	.I2(charge_timer[5]));
   ND2DHD g9400__5115 (.O(n_99),
	.I1(charge_timer[1]),
	.I2(charge_timer[0]));
   INVCKDHD g9427 (.O(n_26),
	.I(tempmin[3]));
   INVCKDHD g9402 (.O(n_25),
	.I(tempmin[4]));
   INVCKDHD g9412 (.O(vmonen),
	.I(cv));
   INVCKDHD g9416 (.O(n_23),
	.I(tmax[1]));
   INVDHD g9440 (.O(n_22),
	.I(charge_timer[2]));
   INVCKDHD g9404 (.O(n_21),
	.I(tempmin[6]));
   INVCKDHD g9430 (.O(n_20),
	.I(tempmin[2]));
   INVCKDHD g9428 (.O(n_19),
	.I(ibat[1]));
   INVCKDHD g9437 (.O(n_18),
	.I(vbat[7]));
   INVCKDHD g9435 (.O(n_17),
	.I(tbat[1]));
   INVCKDHD g9436 (.O(n_16),
	.I(tbat[7]));
   INVCKDHD g9432 (.O(n_15),
	.I(vcutoff[2]));
   INVCKDHD g9420 (.O(n_14),
	.I(vbat[5]));
   INVCKDHD g9429 (.O(n_13),
	.I(ibat[2]));
   INVCKDHD g9417 (.O(n_79),
	.I(vbat[6]));
   INVDHD g9421 (.O(n_39),
	.I(charge_timer[14]));
   INVCKDHD g9438 (.O(n_61),
	.I(vbat[3]));
   INVDHD g9422 (.O(n_40),
	.I(charge_timer[9]));
   INVCKDHD g9439 (.O(n_118),
	.I(charge_timer[0]));
   INVDHD g9443 (.O(n_243),
	.I(state[0]));
   INVDHD g9444 (.O(n_244),
	.I(state[2]));
   INVCKDHD g9425 (.O(n_12),
	.I(tempmin[7]));
   INVCKDHD g9426 (.O(n_11),
	.I(tempmin[5]));
   INVCKDHD g9405 (.O(n_10),
	.I(ibat[6]));
   INVCKDHD g9431 (.O(n_9),
	.I(tbat[6]));
   INVCKDHD g9409 (.O(n_8),
	.I(tbat[4]));
   INVDHD g9441 (.O(n_7),
	.I(charge_timer[4]));
   INVCKDHD g9411 (.O(n_6),
	.I(tbat[3]));
   INVCKDHD g9403 (.O(n_5),
	.I(tempmin[1]));
   INVCKDHD g9434 (.O(n_4),
	.I(tbat[2]));
   INVCKDHD g9406 (.O(n_3),
	.I(ibat[3]));
   INVCKDHD g9415 (.O(n_2),
	.I(vbat[2]));
   INVCKDHD g9414 (.O(n_1),
	.I(tbat[5]));
   INVCKDHD g9433 (.O(n_0),
	.I(vbat[0]));
   INVCKDHD g9407 (.O(n_42),
	.I(ibat[5]));
   INVCKDHD g9413 (.O(n_37),
	.I(tmax[4]));
   INVDHD g9442 (.O(n_214),
	.I(charge_timer[13]));
   INVCKDHD g9408 (.O(n_43),
	.I(ibat[7]));
   INVDHD g9410 (.O(n_38),
	.I(charge_timer[15]));
   INVDHD g9423 (.O(n_197),
	.I(charge_timer[11]));
   INVCKDHD g9419 (.O(n_62),
	.I(vbat[4]));
   INVCKDHD g9418 (.O(n_47),
	.I(vbat[1]));
   INVDHD g9424 (.O(n_240),
	.I(state[1]));
   TIE0DHD tie_0_cell (.O(so));
   TIE1DHD tie_1_cell (.O(logic_1_1_net));
endmodule

